[build]
  command = "npm run build"
  functions = "functions"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/p/*"
  to = "/p/:splat"
  status = 200

[[redirects]]
  from = "/s/*"
  to = "/.netlify/functions/s/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  
[[functions]]
  path = "functions/api/*"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 8888
  framework = "#auto"
  autoLaunch = false
